apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
